# Generated by Django 3.2.7 on 2021-11-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('SPECIALTY', 'SPECIALTY'), ('CONDITION', 'CONDITION'), ('PROCEDURE', 'PROCEDURE')], max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('keywords', models.TextField(max_length=5120)),
            ],
        ),
    ]
