# Generated by Django 3.2.7 on 2021-11-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='categories',
            name='keywords',
            field=models.TextField(max_length=5120, null=True),
        ),
    ]
