# Generated by Django 3.2.6 on 2021-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('FIVE', 5), ('FOUR', 4), ('THREE', 3), ('TWO', 2), ('ONE', 1)], default=1.0),
        ),
    ]
