# Generated by Django 3.2.7 on 2021-11-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0002_auto_20211127_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='sector',
            field=models.CharField(choices=[('SPECIALITY', 'SPECIALITY'), ('CONDITION', 'CONDITION'), ('PROCEDURE', 'PROCEDURE')], max_length=255),
        ),
    ]
