# Generated by Django 3.2.6 on 2021-11-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1.0),
        ),
    ]
