# Generated by Django 3.2.6 on 2021-11-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0002_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SPECIALIST', 'SPECIALIST'), ('USER', 'USER'), ('ADMINISTRATOR', 'ADMINISTRATOR')], default='SPECIALIST', max_length=255),
        ),
    ]
