# Generated by Django 3.2.7 on 2021-12-02 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0004_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('transaction', models.FloatField(null=True)),
                ('message', models.TextField(max_length=5120)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('type', models.CharField(choices=[('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=255)),
                ('note', models.TextField(max_length=5120)),
                ('payment_mode', models.CharField(choices=[('PAYSTACK', 'PAYSTACK'), ('FLUTTERWAVE', 'FLUTTERWAVE'), ('PAYPAL', 'PAYPAL')], default='PAYSTACK', max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_transaction', to='eclinic_platform.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=5120)),
                ('score', models.IntegerField(null=True)),
                ('recommendations', models.TextField(max_length=5120)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eclinic_platform.appointment')),
            ],
        ),
    ]
