# Generated by Django 3.2.7 on 2021-11-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0006_auto_20211128_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default='null', max_length=5120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(null=True, upload_to='usersBg'),
        ),
        migrations.AddField(
            model_name='user',
            name='header_title',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='location_address',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='location_address_component',
            field=models.TextField(default='null', max_length=5120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='location_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_long',
            field=models.FloatField(null=True),
        ),
    ]
