# Generated by Django 3.2.7 on 2021-11-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0008_auto_20211128_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_long',
            new_name='location_lng',
        ),
    ]
