# Generated by Django 3.2.7 on 2021-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0008_auto_20211129_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_enabled', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('whatsapp_number', models.CharField(max_length=50, null=True)),
                ('zoom_enabled', models.BooleanField(default=True)),
                ('zoom_link', models.CharField(max_length=255, null=True)),
                ('google_meet_enabled', models.BooleanField(default=True)),
                ('google_meet_link', models.CharField(max_length=255, null=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_address', models.EmailField(max_length=250, null=True)),
            ],
        ),
    ]
