# Generated by Django 3.2.7 on 2021-11-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0009_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='user',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='eclinic_platform.user'),
            preserve_default=False,
        ),
    ]
