# Generated by Django 3.2.7 on 2021-11-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0009_rename_location_long_user_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
    ]
