# Generated by Django 3.2.7 on 2021-11-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0010_user_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avg_rating',
            field=models.FloatField(default=1, max_length=5),
        ),
    ]
