# Generated by Django 3.2.7 on 2021-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0011_alter_user_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elders_Checkup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='home_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='online_Consult',
            field=models.BooleanField(default=True),
        ),
    ]
