# Generated by Django 3.2.7 on 2021-11-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0012_alter_communication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='communication_mode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='eclinic_platform.communication'),
        ),
    ]
