# Generated by Django 3.2.7 on 2021-11-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic_platform', '0012_auto_20211128_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='elders_Checkup',
            new_name='checkup_Someone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='home_service',
            new_name='home_Service',
        ),
    ]
